---
title: "Modeling_Scenarios"
output: html_document
date: "2022-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
require(pacman)
pacman::p_load(tidyverse, # keep things tidy
               googlesheets4, # read_sheet 
               googledrive) # drive_ functions

#double check your wd. should be ../rc_sfa-rc-3-wenas-modeling
#if not you need to do new relative file pathing

getwd()
```

## Read in Model Outputs 

```{r read in data, echo=FALSE}
## Set GDrive URL for files
directory = "https://drive.google.com/drive/folders/1MtvqmPVif1dLWZbM8ORFvfjQpZohMoS7"

read_data <- function(data){
  # First, scrape scenario name from file name
  scenario <- stringr::word(data, sep= fixed(".c"))
  # Second, read in data
  read.csv(file = data) %>% 
    mutate(scenario = scenario)
}

## Create a list of files to download
files <- drive_ls(directory) %>% 
  filter(grepl("_results", name))

## Download files to local (don't worry, we'll delete em in a sec)
lapply(files$name, drive_download, overwrite = TRUE)

## Read in data, filter to EC1 samples, and add sample name
all_outputs <- files$name %>% 
  map(read_data) %>% 
  bind_rows()

all_outputs$dates <- as.POSIXct(all_outputs$dates)

key = googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1fM_JKnCXQ9uUFaplQ90YwZevvnrnpSp_R26KsN8tHdM/edit#gid=0", sheet = 1)

all_outputs_wmeta <- full_join(all_outputs, key, by=c("scenario"))

## Clean up local (delete downloaded files)
file.remove(c(files$name))

```

```{r sanity check, echo=FALSE}

Base = all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Base Case")) %>%
  filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit()

max(Base$nit_mgL_.chg)
min(Base$nit_mgL_.chg)

areasev = all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Area Burned x Severity"))%>%
  filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit()

max(areasev$nit_mgL_.chg)
min(areasev$nit_mgL_.chg)
```

## Make some prelim plots!

Plot the daily %changes for the whole period by scenario group first
Groups are:
Area Burned x Severity 
Land Use
Climate
Flow Pathways
Basin Slope 


```{r plots plots plots, echo=FALSE}

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Base Case")) %>%
  filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
  filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg))+
  geom_density()+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="none", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Area Burned x Severity")) %>%
   filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
   filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg, fill=ShortScenario))+
  geom_density(alpha=0.4)+
  geom_density()+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="left", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Land Use")) %>%
   filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
   filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg, fill=ShortScenario))+
  geom_density(alpha=0.4)+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="left", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Climate")) %>%
   filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
   filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg, fill=ShortScenario))+
  geom_density(alpha=0.4)+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="left", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Flow Pathways")) %>%
   filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
   filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg, fill=ShortScenario))+
  geom_density(alpha=0.4)+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="left", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())

all_outputs_wmeta %>% 
  filter(ScenarioGroup %in% c("Basin Slope")) %>%
   filter(between(dates, as.POSIXct("2020-01-01"), as.POSIXct("2020-12-31"))) %>%
  na.omit() %>%
   filter(nit_mgL_.chg > 10) %>%
  ggplot(aes(x=nit_mgL_.chg, fill=ShortScenario))+
  geom_density(alpha=0.4)+
  theme_classic()+
  labs(y = "density", x = "% Change in Nitrate from Base Unburnt Condition")+
  theme(legend.position="left", 
        plot.title =  element_text(size=12),axis.text.y=element_text(size=12,
                                                                     color="black"),
        axis.title.y=element_text(size=12),
        strip.text = element_text(size = 9, color= "black"))+
  theme(strip.background = element_blank())
```
