---
title: "AMP_AGU"
author: "AMP"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries}
library(tidyverse)
library(stringr)
library(usmap)
library(segmented)
library(strucchange)
getwd()

essdive_template_cleaning <- function(dataframe){
  cleaned <- dataframe %>% 
  janitor::row_to_names(row_number = which(dataframe[,1] == "Field_Name")) %>% #this assumes that this name is somewhere in column #1. That follows some (most?) ESS-DIVE templates.
 slice(which(Field_Name == "#Start_Data"):which(Field_Name == "#End_Data")) %>%
 select(!Field_Name)
  }
```

Wenas Creek MODEX 
```{r wenas}
Wenas_CN <- read_csv("../../wenas-hackathon/Wenas_Data_Package/YRBT_Water_NPOC_TN.csv") %>% 
  essdive_template_cleaning() %>%
  rename(NPOC_mg_C_per_L = `00681_NPOC_mg_per_L_as_C`,
         TN_mg_N_per_L = `00602_TN_mg_per_L_as_N`) %>%
   select(Sample_Name, NPOC_mg_C_per_L, TN_mg_N_per_L) %>%
  filter(grepl('filt0.2', Sample_Name)) %>%
  mutate(Sample_Name = stringr::str_remove(Sample_Name ,"-filt0.2"),
         NPOC_mg_C_per_L = case_when(NPOC_mg_C_per_L == -9999 ~ NA,
                              str_detect(NPOC_mg_C_per_L, "LOD") ~ NA,
                              str_detect(NPOC_mg_C_per_L, "Below_0.1_ppm") ~
                                      forstringr::str_extract_part(NPOC_mg_C_per_L, "_ppm_Below_0.1_ppm", before = TRUE),
                               TRUE ~ NPOC_mg_C_per_L),
         TN_mg_N_per_L = case_when(TN_mg_N_per_L == -9999 ~ NA,
                              str_detect(TN_mg_N_per_L, "LOD") ~ NA,
                              str_detect(TN_mg_N_per_L, "Below_0.1_ppm") ~ 
                                        forstringr::str_extract_part(TN_mg_N_per_L, "_ppm_Below_0.1_ppm", before = TRUE),
                               TRUE ~ TN_mg_N_per_L)) %>%
  mutate(NPOC_mg_C_per_L = case_when(str_detect(NPOC_mg_C_per_L, "NPOC_") ~ 
                                     str_extract(NPOC_mg_C_per_L, "0.(\\d+)"),
                                     NPOC_mg_C_per_L < 0 ~ NA,
                                     TRUE ~ NPOC_mg_C_per_L),
         TN_mg_N_per_L = case_when(str_detect(TN_mg_N_per_L, "TN_") ~ 
                                     str_extract(TN_mg_N_per_L, "0.(\\d+)"),
                                     TN_mg_N_per_L < 0 ~ NA, 
                                     TRUE ~ TN_mg_N_per_L)) %>%
  mutate(Site = str_extract(Sample_Name, "(?<=YRBT_)[:alnum:]{3}")) %>% 
  mutate_at(vars(ends_with("per_L")), as.numeric)

#changing site ID to locations 
Wenas_CN$Site[grepl('W10', Wenas_CN$Site)] <-'Reference'
Wenas_CN$Site[grepl('W20', Wenas_CN$Site)] <-'Burned'
```
```{r wenas figs} 
#NPOC plot and stats
NPOC_plot <- ggplot(Wenas_CN, aes(x=Site, y=NPOC_mg_C_per_L, fill = Site))+geom_boxplot()+
  theme_classic()+
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, color = "black", angle= 45, hjust = 1))+
  scale_fill_manual(values = PNWColors::pnw_palette("Moth"))+
  ylab(expression(paste(Dissolved~Organic~Carbon~(mg~L^-1), sep="")))+
  theme(legend.position = "none")+
  annotate(geom="text", size = 7, x = 1.5, y = 6, label = "p = 0.44", color ="black")

kruskal.test(NPOC_mg_C_per_L~Site, data = Wenas_CN)

pdf(paste0("../figures/agu_amp/", 
           "Wenas_NPOC_boxplot.pdf"), width=3.5, height=6)
print(NPOC_plot)
dev.off()

#TN plot and stats
TN_plot <- ggplot(Wenas_CN, aes(x=Site, y=TN_mg_N_per_L, fill = Site))+geom_boxplot()+
  theme_classic()+
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, color = "black", angle=45, hjust = 1))+
 scale_fill_manual(values = PNWColors::pnw_palette("Moth"))+
  ylab(expression(paste(Total~Dissolved~Nitrogen~(mg~L^-1), sep="")))+
  theme(legend.position = "none")+
  annotate(geom="text", size = 7, x = 1.5, y = 0.75, label = "p = 0.39", color ="black")

kruskal.test(TN_mg_N_per_L~Site, data = Wenas_CN)

pdf(paste0("../figures/agu_amp/", 
           "Wenas_TDN.pdf"), width=3.5, height=6)
print(TN_plot)
dev.off()
```
```{r tss}
#TSS plot and stats
Wenas_TSS <- read_csv("../../wenas-hackathon/Wenas_Data_Package/YRBT_Water_TSS.csv") %>%
  essdive_template_cleaning() %>%
  rename(TSS_mg_L = `00530_TSS_mg_per_L`) %>%
  select(Sample_Name, TSS_mg_L) %>%
  mutate(Sample_Name = stringr::str_remove(Sample_Name ,"-unfilt"),
         TSS_mg_L = case_when(TSS_mg_L == -9999 ~ NA,
                              str_detect(TSS_mg_L, "LOD") ~ NA,
                               TRUE ~ TSS_mg_L)) %>%
  mutate(Site = str_extract(Sample_Name, "(?<=YRBT_)[:alnum:]{3}")) %>% 
  mutate_at(vars(ends_with("_L")), as.numeric) %>% na.omit()

Wenas_TSS$Site[grepl('W10', Wenas_TSS$Site)] <-'Reference'
Wenas_TSS$Site[grepl('W20', Wenas_TSS$Site)] <-'Burned'

tss_plot <- ggplot(Wenas_TSS, aes(x=Site, y=TSS_mg_L, fill = Site))+geom_boxplot()+
  theme_classic()+
  theme(axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 15, color = "black", angle= 45, hjust = 1))+
scale_fill_manual(values = PNWColors::pnw_palette("Moth"))+
  ylab(expression(paste(Total~Suspended~Solids~(mg~L^-1), sep="")))+
  theme(legend.position = "none")+
  annotate(geom="text", size = 7, x = 1.5, y = 100, label = "p = 0.32", color ="black")

kruskal.test(TSS_mg_L~Site, data = Wenas_TSS)  

pdf(paste0("../figures/agu_amp/", 
           "Wenas_TSS.pdf"), width=3.5, height=6)
print(tss_plot)
dev.off()
```

```{r wenas map}
wenas_loc <- data.frame(lon = -120.7109202, lat = 46.83285283)

transformed_data <- usmap_transform(wenas_loc)

plot_usmap("states") + 
  ggstar::geom_star(data = transformed_data, 
             aes(x = x, y = y), 
             color = "red",
             size = 3)

ggsave("../figures/agu_amp/wenas_map.png")


```

#model results 
```{r model results}
theme_set(theme_classic())

nitrate_line <- ggplot(df_means, aes(percent, nitrate_perc, color = severity)) + 
  # geom_vline(xintercept=rust_mean_percent_area_burn, linetype="dashed")+
  geom_vline(xintercept=82, linetype="dashed", color="red")+
 #  geom_vline(xintercept=33, linetype="dashed")+
    geom_point(alpha = 0.2) + 
    geom_smooth(se=F)+
    scale_color_manual(values = severity_colors) +
    labs(x = "Simulated % of watershed burned", 
         y = "Mean % Change (NO3, mg/L)", 
         color = "Fire \n Severity") + 
    theme(axis.title = element_text(size = 15),
          axis.text = element_text(size = 15),
          legend.title = element_text(hjust = 0.5))

ggsave("../figures/agu_amp/nitrate_mean_line.png", plot = nitrate_line)

doc_line <- ggplot(df_means, aes(percent, doc_perc, color = severity)) +
#  geom_vline(xintercept=rust_mean_percent_area_burn, linetype="dashed")+
  geom_vline(xintercept=82, linetype="dashed", color="red")+
  # geom_vline(xintercept=33, linetype="dashed")+
    geom_point(alpha=0.2) + 
    geom_smooth(se=F)+
    scale_color_manual(values = severity_colors) +
    labs(x = "Simulated % of watershed burned", 
         y = "Mean % Change (DOC, mg/L)", 
         color = "Fire \n Severity") + 
    theme(axis.title = element_text(size = 15),
          axis.text = element_text(size = 15),
          legend.title = element_text(hjust = 0.5))

ggsave("../figures/agu_amp/doc_mean_line.png", plot = doc_line)
  
tss_line <- ggplot(df_means, aes(percent, sed_perc, color = severity)) + 
#   geom_vline(xintercept=rust_mean_percent_area_burn, linetype="dashed")+
  geom_vline(xintercept=87, linetype="dashed", color="red")+
  # geom_vline(xintercept=33, linetype="dashed")+
   geom_point(alpha=0.2) + 
     geom_smooth(se=F)+
    scale_color_manual(values = severity_colors) +
    labs(x = "Simulated % of watershed burned", 
         y = "Mean % Change (TSS, mg/L)", 
         color = "Fire \n Severity") + 
    theme(axis.title = element_text(size = 15),
          axis.text = element_text(size = 15),
          legend.title = element_text(hjust = 0.5))

ggsave("../figures/agu_amp/tss_mean_line.png", plot = tss_line)


```
Rust et al percent changes 
```{r rust}

rust <- readxl::read_excel("../data/rust_percent_change.xlsx")

rust_mean_percent_area_burn = 18

rust_fig <- ggplot(rust, aes(variable, percent_change_concentration, fill = variable)) + 
    geom_col() + 
    scale_fill_manual(values = PNWColors::pnw_palette("Winter")) +
    labs(x = "Water Quality Variable", 
         y = "Mean Percent Change in Western CONUS (%)") + 
    theme(axis.title = element_text(size = 15),
          axis.text = element_text(size = 15),
          legend.title = element_text(hjust = 0.5))

ggsave("../figures/agu_amp/rust_fig.png", plot = rust_fig)

rust_fig 
```

### finding a change point
```{r change pt v1}
model <- lm(doc_mg_l_fire ~ percent, data = df_means) #makes model
seg_model <- segmented(model, seg.Z = ~percent, psi = c(75)) #makes segmented model, psi estimates breakpoint location
# Print the segmented regression model 
summary(seg_model) 
```

```{r change point by severity}
model <- lm(doc_mg_l_fire ~ percent, data = df_means %>% filter(severity == "LOW")) 
seg_model <- segmented(model, seg.Z = ~percent, psi = c(75)) 
 
# Print the segmented regression model 
summary(seg_model)

model.mod <- lm(doc_mg_l_fire ~ percent, data = df_means %>% filter(severity == "LOW")) 
seg_model.mod <- segmented(model, seg.Z = ~percent, psi = c(75)) 
 
# Print the segmented regression model 
summary(seg_model.mod)
```
```{r change point w function}
seg_model <- function(var, psi_value){
 
  formula = as.formula(paste(var, "~ percent"))
  
  low_model <- lm(formula, data = df_means %>% filter(severity == "LOW"))
  mod_model <- lm(formula, data = df_means %>% filter(severity == "MOD"))
  high_model <- lm(formula, data = df_means %>% filter(severity == "HIGH"))
  
  low_seg_model <- segmented(low_model, seg.Z = ~percent, psi = c(psi_value))
  mod_seg_model <- segmented(mod_model, seg.Z = ~percent, psi = c(psi_value))
  high_seg_model <- segmented(high_model, seg.Z = ~percent, psi = c(psi_value))
  
  as_tibble(summary(low_seg_model)[[12]]) %>% 
    add_row(as_tibble(summary(mod_seg_model)[[12]])) %>% 
    add_row(as_tibble(summary(mod_seg_model)[[12]])) %>% 
    mutate(severity = c("LOW", "MOD", "HIGH")) %>% 
    mutate(var = var)
}

bind_rows(seg_model("sed_mg_l_fire", 75), 
          seg_model("nit_mg_l_fire", 75), 
          seg_model("doc_mg_l_fire", 75))

```
