---
title: "Manuscript Figures"
author: "AMP"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

 # load packages
 require(pacman)
 pacman::p_load(hydroTSM,
                readr,
                gridExtra,
                viridis,
                ggthemes,
                RColorBrewer,
                scales,
                tidyverse, # keep things tidy!!
                googlesheets4, # read_sheet
                googledrive, # google drive access
                ggplot2, #plotting
                PNWColors ) # pretty colors 

 #double check your wd. should be ../rc_sfa-rc-3-wenas-modeling/scripts
 #if not you need to do new relative file pathing!

 getwd()
```

#load data

Load the L1 data here since we dont need or want the percent changes. 

```{r}

load("~/GitHub/rc_sfa-rc-3-wenas-modeling/data/outputs/2023-10-05_output_datset_L1.rda")

```

organize the datasets a little bit

```{r}
percent_outputs <- outputs_final %>%
  filter(climate == "base" & land_use == "base" & hydrology == "base" & slope == "base") %>%
    mutate(severity = fct_relevel(severity, "HIGH","MOD","LOW", "base"),
           percent= fct_relevel(percent, "base", "10", "15", "20","25", "30", "40", "45", "50", "60", "75", "90", "100"),
           percent_groups = case_when(percent == "10"| percent == "15"| percent == "20" ~ "10-20",
                                      percent == "25"| percent == "30"| percent == "40" ~ "25-40",
                                      percent == "45"| percent == "50"| percent == "60" ~ "45-60",
                                      percent == "75"| percent == "90"| percent == "100" ~ "75-100" ),
           percent_groups = fct_relevel(percent_groups, "10-20","25-40","45-60", "75-100" ))
```

Now, work on manipulating the data to make the flow duration plots

```{r function from Katie}
get_percent <- function(df, scenarios){
  for (x in scenarios){
    df_sub <- subset(df, df$short_scenario == x)
    df_sub <- df_sub[order(df_sub$flow_m3s_fire, decreasing=T),]
    df_sub$rank <- 1:nrow(df_sub)
    df_sub$prob <- 100 *  (df_sub$rank / (nrow(df_sub) + 1))
    if(x == scenarios[1]){
      df_done <- df_sub
    } else{df_done <- rbind(df_done, df_sub)}}
    df_done
}
```

```{r data prep a different way}
Qdat <-  percent_outputs %>%
  group_by(short_scenario) %>%
  filter(!scenario == "base_burned") %>%
  filter(!percent == "base") %>%
  pivot_longer(cols = contains("flow"),
               names_to = "flow_type",
               values_to = "flow_m3s") %>%
  group_by(flow_type,short_scenario) %>%
  mutate(rank = rank(-flow_m3s)) %>%
  mutate(P = 100 * (rank / (length(flow_m3s) + 1)))

View(Qdat)
```

#Figure 1: Simulated Hydrologic Responses 

```{r Figure 1}

severity_colors_rev = c("#F21A00",  "#E1AF00",  "#3B9AB2","black")

Qdat %>% 
  filter(percent_groups == "75-100") %>%
  group_by(percent) %>%
  ggplot()+
  geom_line(aes(x = P, y = flow_m3s, color= percent, linetype = flow_type))+
  scale_y_log10()+
  xlab("% Time flow equalled or exceeded")+
  ylab(expression(paste("Simulated Streamflow (", m^{3}," ",sec^{-1}, ")")))+
    theme_classic() +
    scale_color_manual(values = severity_colors_rev)+
  facet_wrap(~factor(severity), nrow = 1, 
             labeller = label_wrap_gen(10))

```


